114 teeth brushing
Monstie-Wash/G10_MonstieWash pull request #15
Opened 2024-04-13 04:17 UTC by 102101141

Made bubble particle system (PS, texture, reflections).
Added ToolVFX script.
Added ToolFVX script to brush prefab.
Added everything to InputManager.

2024-04-13 04:26 UTC, CrispyKorn requested changes
All looks good, just a couple tweaks and also don't forget to also change the simulation space on the Bubble_Sub_PS from local to world space so that when the bubbles pop those particles are also in world space. Other than that, all good!

2024-04-13 04:26 UTC, CrispyKorn commented on MonstieWash/Assets/Scripts/VFX/ToolFX.cs
> +    ParticleSystem myParticles;
Just convention stuff.
```suggestion
    private ParticleSystem m_myParticles;
```

2024-04-13 04:26 UTC, CrispyKorn commented on MonstieWash/Assets/Scripts/VFX/ToolFX.cs
> +    /// </summary>
Can remove these lines (they were from the eraser script).

```suggestion
```

2024-04-13 04:26 UTC, CrispyKorn commented on MonstieWash/Assets/Scripts/VFX/ToolFX.cs
> +        Debug.Log("Subscribed");
Don't need this anymore.
```suggestion
```

2024-04-15 02:04 UTC, closed without merging

2024-04-15 02:05 UTC, 102101141 commented
Had to do further modification of this code that rendered this PR obsolete: ToolFX script couldn't subscribe to the InputManager properly because it had no context of whether the tool was being held or not, and thus the particles would play even while the tool was unattended. New PR will fix this problem by including the functionality in the eraser script.